lifelist-master/config/routes.rb
Lifelist::Application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                    registrations: 'users/registrations',
                                    sessions: 'users/sessions' }

  root to: 'explore#index', :as => "explore"
  get 'terms' => 'main#terms'
  get 'privacy' => 'main#privacy'
  resources 'invite_requests'

  resources :goals do
    get 'featured', :on => :collection
    member do
      get 'pathways'
      put 'add_to_lifelist'
      put 'add_to_doneit'
      put 'toggle_vote'
      put 'crop'
    end
  end
  match 'explore' => 'explore#index'
  match 'explore/:topic' => 'explore#topic'
  scope "api" do
    resources :categories, only: [:index]
  end

  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :users, only: [:update]
  get '/profile/edit' => 'users#edit', as: :edit_profile

  match ':username' => 'users#show', as: :profile
  namespace :users, path: ':username' do
    resources :goals do
      get 'featured', :on => :collection
      member do
        get 'autoassign_image'
        put 'sort'
      end
      resources :steps do
        put 'sort', on: :member
      end
    end
  end
end

lifelist-master/app/controllers/explore_controller.rb
class ExploreController < ApplicationController
  before_filter :authenticate_user!, except: :index

  def index
    if user_signed_in?
      @goals = Goal.hierarchs.where(:featured => true).order("id desc").paginate(:per_page => 16, :page => params[:page])
      @goals_listed = current_user.goals_listed
      @goals_done= current_user.goals_done
      if request.xhr?
        sleep(1)
        render partial: 'explore/explore_rows', locals: { goals: @goals }
      end
    else
      @invite_request = InviteRequest.new
      render template: 'devise/sessions/new'
    end
  end


  def topic
    @tag = ActsAsTaggableOn::Tag.where("LOWER(name) = ?", params[:topic].gsub("_and_", " & ")).first
    if @tag.nil?
      redirect_to :action=>"index" 
      return
    end
    @goals = Goal.tagged_with(@tag.name).where(:featured => true).order("id desc").paginate(:per_page => 16, :page => params[:page])
    if request.xhr?
      sleep(1)
      render partial: 'explore/explore_rows', locals: { goals: @goals }
    end
    render :action=>"index"
  end
  
end

lifelist-master/app/views/explore/_explore_rows.html.haml
- sequence_offset ||= 0
- crop_form_builder ||= nil
- goals.each_with_index do |goal, index|
  - sequence_index = index + sequence_offset
  - next_goal = goals[index + 1]
  - if index % 2 == 0
    .row-fluid
      = render goal, index: sequence_index, crop_form_builder: crop_form_builder
      = render next_goal, index: sequence_index + 1, crop_form_builder: crop_form_builder if next_goal.present?

lifelist-master/app/views/explore/index.html.haml
- content_for :head do
  = stylesheet_link_tag 'pageless-loader'
  = javascript_include_tag 'pageless/lib/jquery.pageless'
  :javascript
    var goals_listed = #{@goals_listed};
    var goals_done= #{@goals_done};

#explore-wrap.container-fluid
  = render partial: 'explore_rows', locals: { goals: @goals }
  = will_paginate(@goals)
  = render partial: 'pageless_loader'
  = pageless(@goals.total_pages, explore_path, 'explore-wrap')