lifelist-master/config/routes.rb
Lifelist::Application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                    registrations: 'users/registrations',
                                    sessions: 'users/sessions' }

  root to: 'explore#index', :as => "explore"
  get 'terms' => 'main#terms'
  get 'privacy' => 'main#privacy'
  resources 'invite_requests'

  resources :goals do
    get 'featured', :on => :collection
    member do
      get 'pathways'
      put 'add_to_lifelist'
      put 'add_to_doneit'
      put 'toggle_vote'
      put 'crop'
    end
  end
  match 'explore' => 'explore#index'
  match 'explore/:topic' => 'explore#topic'
  scope "api" do
    resources :categories, only: [:index]
  end

  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :users, only: [:update]
  get '/profile/edit' => 'users#edit', as: :edit_profile

  match ':username' => 'users#show', as: :profile
  namespace :users, path: ':username' do
    resources :goals do
      get 'featured', :on => :collection
      member do
        get 'autoassign_image'
        put 'sort'
      end
      resources :steps do
        put 'sort', on: :member
      end
    end
  end
end

lifelist-master/app/views/layouts/_image_upload.html.haml
.fileupload.imageupload{ 'data-provides' => 'fileupload', class: image_url ? 'fileupload-exists' : 'fileupload-new' }
  .fileupload-new.thumbnail
    = image_tag 'http://www.placehold.it/200x200'
  .fileupload-preview.fileupload-exists.thumbnail
    = image_tag @user.avatar_url if current_user.avatar.present?
  %div
    %span.btn.btn-file
      %span.fileupload-new Select image
      %span.fileupload-exists Change
      = builder.file_field :avatar
    / TODO: Make this persist with hidden remove_avatar input
    %a.btn.fileupload-exists{ 'data-dismiss' => 'fileupload', href: '#' } Remove

lifelist-master/app/views/layouts/_kissmetrics.html.erb
<script type="text/javascript">
  var _kmq = _kmq || [];
  var _kmk = _kmk || '27fd701961159c276ebb199651501f167a8ff1b5';
  function _kms(u){
    setTimeout(function(){
      var d = document, f = d.getElementsByTagName('script')[0],
      s = d.createElement('script');
      s.type = 'text/javascript'; s.async = true; s.src = u;
      f.parentNode.insertBefore(s, f);
    }, 1);
  }
  _kms('//i.kissmetrics.com/i.js');
  _kms('//doug1izaerwt3.cloudfront.net/' + _kmk + '.1.js');
</script>

lifelist-master/app/views/layouts/_mixpanel.html.erb
  <!-- start Mixpanel --><script type="text/javascript">(function(e,b){if(!b.__SV){var a,f,i,g;window.mixpanel=b;a=e.createElement("script");a.type="text/javascript";a.async=!0;a.src=("https:"===e.location.protocol?"https:":"http:")+'//cdn.mxpnl.com/libs/mixpanel-2.2.min.js';f=e.getElementsByTagName("script")[0];f.parentNode.insertBefore(a,f);b._i=[];b.init=function(a,e,d){function f(b,h){var a=h.split(".");2==a.length&&(b=b[a[0]],h=a[1]);b[h]=function(){b.push([h].concat(Array.prototype.slice.call(arguments,0)))}}var c=b;"undefined"!==
  typeof d?c=b[d]=[]:d="mixpanel";c.people=c.people||[];c.toString=function(b){var a="mixpanel";"mixpanel"!==d&&(a+="."+d);b||(a+=" (stub)");return a};c.people.toString=function(){return c.toString(1)+".people (stub)"};i="disable track track_pageview track_links track_forms register register_once alias unregister identify name_tag set_config people.set people.increment people.append people.track_charge people.clear_charges people.delete_user".split(" ");for(g=0;g<i.length;g++)f(c,i[g]);b._i.push([a,
  e,d])};b.__SV=1.2}})(document,window.mixpanel||[]);
  mixpanel.init("19c06f5f407916f3d14d5de54265e9ce");</script><!-- end Mixpanel -->

lifelist-master/app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-fixed-top
  .navbar-inner.container
    %a{:href => "/", :class=>"logo" }
    .nav-collapse
      %ul.nav
        %li.categories.dropdown{class: is_active?(:explore, :index)}
          %a.dropdown-toggle{:href => explore_path}
            Explore
          %ul.dropdown-menu.clearfix
            %li
              %a{:href => "/explore/adventure"}Adventure
            %li
              %a{:href => "/explore/entertainment"}Entertainment
            %li
              %a{:href => "/explore/travel"}Travel
            %li
              %a{:href => "/explore/habits"}Habits
            %li
              %a{:href => "/explore/spiritual"}Spiritual
            %li
              %a{:href => "/explore/athletics"}Athletics
            %li
              %a{:href => "/explore/health_and_nutrition"}Health & Nutrition
            %li
              %a{:href => "/explore/education"}Education
            %li
              %a{:href => "/explore/skills"}Skills
            %li
              %a{:href => "/explore/art"}Art
            %li
              %a{:href => "/explore/music_and_dance"}Music &amp; Dance
            %li
              %a{:href => "/explore/literature"}Literature
            %li
              %a{:href => "/explore/financial"}Financial
            %li
              %a{:href => "/explore/professional"}Professional
            %li
              %a{:href => "/explore/altruistic"}Altruistic
            %li
              %a{:href => "/explore/environment"}Environment
            %li
              %a{:href => "/explore/animals"}Animals
            %li
              %a{:href => "/explore/family"}Family
            %li
              %a{:href => "/explore/relationships"}Relationships
        - if user_signed_in?
          %li{class: is_active?(:users, :show) || is_active?('users/goals', :show)}
            = link_to 'Lifelist', profile_path(current_user)
      %ul.nav.pull-right
        %li.search
          = form_tag '' do
            = text_field_tag :search, nil, placeholder: 'Search...', class: 'swiftype st-search-input', autocomplete: :off
        - if user_signed_in?
          %li.settings.dropdown
            %a.dropdown-toggle.profile{"data-toggle" => "dropdown", :href => "#"}
              %i.icon-settings
              %span.caret
            %ul.dropdown-menu
              %li.edit-settings
                = image_tag current_user.avatar_url(:thumb) if current_user.avatar.present?
                %strong
                  = current_user.first_name
                  = current_user.last_name
              %li= link_to 'Settings', edit_profile_path
              %li= link_to 'Help', profile_path(current_user)
              %li= link_to 'Logout', destroy_user_session_path, method: :delete

lifelist-master/app/views/layouts/_uservoice.html.erb
<script type="text/javascript">
  var uvOptions = {};
  (function() {
    var uv = document.createElement('script'); uv.type = 'text/javascript'; uv.async = true;
    uv.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'widget.uservoice.com/mbfRPJWDWDiRvnS2P1KEWQ.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(uv, s);
  })();
</script>

lifelist-master/app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Lifelist
    = stylesheet_link_tag    "application", :media => "all"
    = stylesheet_link_tag    "http://fonts.googleapis.com/css?family=Open+Sans:400,300"
    = stylesheet_link_tag    "http://fonts.googleapis.com/css?family=Montserrat"
    = render partial: 'layouts/remove_fb_url_fragment'
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield :head
  %body{class:"#{controller_name} #{action_name} #{user_signed_in? ? 'logged-in' : 'logged-out'}"}
    %header
      = render partial: 'layouts/navbar'
      - # todo: prettier flashes and make them visible on landing page
      - flash.each do |name, msg|
        - if msg.is_a?(String)
          %div{:class => "alert alert-large alert-#{name == :notice ? "success" : "error"} container"}
            %a.close{"data-dismiss" => "alert"} ×
            = content_tag :div, msg, :id => "flash_#{name}"
    #main-wrap.container
      = yield
      = render partial: 'layouts/ga'
      = render partial: 'layouts/mixpanel'
      = render partial: 'layouts/uservoice'