lifelist-master/config/routes.rb
Lifelist::Application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                    registrations: 'users/registrations',
                                    sessions: 'users/sessions' }

  root to: 'explore#index', :as => "explore"
  get 'terms' => 'main#terms'
  get 'privacy' => 'main#privacy'
  resources 'invite_requests'

  resources :goals do
    get 'featured', :on => :collection
    member do
      get 'pathways'
      put 'add_to_lifelist'
      put 'add_to_doneit'
      put 'toggle_vote'
      put 'crop'
    end
  end
  match 'explore' => 'explore#index'
  match 'explore/:topic' => 'explore#topic'
  scope "api" do
    resources :categories, only: [:index]
  end

  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :users, only: [:update]
  get '/profile/edit' => 'users#edit', as: :edit_profile

  match ':username' => 'users#show', as: :profile
  namespace :users, path: ':username' do
    resources :goals do
      get 'featured', :on => :collection
      member do
        get 'autoassign_image'
        put 'sort'
      end
      resources :steps do
        put 'sort', on: :member
      end
    end
  end
end

lifelist-master/app/models/goal.rb
class Goal < ActiveRecord::Base
  # after_create :autoassign_image

  attr_accessible :category_id, :description, :name, :user_id, :featured,
  :position, :goal_image_id, :goal_image_attributes, :status, :parent_goal_id,
  :topic_list
  attr_accessor :feature_image_url, :current_user

  belongs_to :user
  has_many :steps, dependent: :destroy
  belongs_to :category
  validates_presence_of :name
  belongs_to :goal_image
  belongs_to :parent_goal, class_name: 'Goal', foreign_key: :parent_goal_id
  accepts_nested_attributes_for :goal_image, update_only: true
  default_scope where(published_at: nil).order('updated_at desc')
  scope :hierarchs, where(parent_goal_id: nil)
  before_create :increment_position
  before_create :set_parent_id
  delegate :image, :image_url, to: :goal_image, allow_nil: true
  acts_as_voteable

  include Searchable
  include Publishable

  class << self

    def image_version_at index
      index = index % 6
      pattern = [:two_thirds, :one_third, :one_third, :two_thirds, :one_half, :one_half]
      pattern[index]
    end

    def span_class_at index
      spans = { one_third: 'span4', two_thirds: 'span8', one_half: 'span6' }
      image_version = Goal.image_version_at index
      "#{image_version.to_s} #{spans[image_version]}"
    end
  end

  def autoassign_image
    if self.goal_image.nil?
      self.goal_image = GoalImage.where(:category_id => nil, :keywords => "default").first
      self.save
    end
  end
  
  def copy_to_user(user, opts={})

    copy_steps = opts[:copy_steps].nil? ? true : opts[:copy_steps]
    status = opts[:status] || "To-do"

    return user.my_version_of_goal(self) if user.has_added_goal?(self)
    
    new_goal = self.dup
    new_goal.user_id = user.id
    new_goal.featured = false
    new_goal.parent_goal_id = self.id
    new_goal.status =  status
    
    new_goal.goal_image = self.goal_image
    #new_goal.image.recreate_versions!
    
    new_goal.save

    if copy_steps
      self.steps.each do |step|
        new_step = step.dup
        new_step.goal_id = new_goal.id
        new_step.user_id = new_goal.user_id
        new_step.completed = false
        new_step.save
      end
    end

    new_goal
  end

  def added_by_user?(user=nil)
    user ||= current_user
    user.has_added_goal?(self) if user.present?
  end
  
  def explore_button_for_user
    self.added_by_user? ?  "list_button_done.png" : "list_button.png"
  end

  def feature_image_url index=0
    self.image_url(Goal.image_version_at(index))
  end

  def absolute_url
    Rails.application.routes.url_helpers.send("#{self.class.name.downcase}_url", self,
                                                  host: Rails.configuration.action_mailer.default_url_options[:host])
  end

  def should_index
    parent_goal_id == nil
  end

  def pathways
    # pathways are published goals (collection of steps)
    goals_with_pathways = Goal.where('published_goal_id is not null').where(parent_goal_id: id)
    goals_with_pathways.unshift self if published?
    goals_with_pathways.map(&:published_goal).sort_by!(&:votes_count).reverse
  end

  private

  def increment_position
    unless user.blank?
      previous_position = user.goals.last.position if user.goals.present?
      if previous_position == nil # self is the first step in this goal
        self.position = 0
      else
        self.position = previous_position + 1
      end
    end
  end

  def set_parent_id
    # don't allow goals to be created with a name different than their parent
    # (this would happen if a user selected a goal from autocomplete and then changed the name)
    unless parent_goal_id.blank? || Goal.find(parent_goal_id).name == name
      self.parent_goal_id = nil
    end
  end
end

lifelist-master/app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  # before_filter :authenticate_user!, except: [:index, :show]
  before_filter :authenticate_admin_user!, only: [:edit, :crop]
  respond_to :json

  def index
    respond_with Goal.all
  end

  def show
    @user = current_user
    @goal = Goal.find(params[:id])
    respond_to do |format|
      format.json {
        respond_with @goal.as_json(methods: :feature_image_url)
      }
      format.html {
        @goal.copy_to_user(current_user) if params[:listed]
      }
    end
  end

  def create
    respond_with current_user.goals.create(params[:goal]), location: goals_url
  end

  def edit
    @goal = Goal.find(params[:id])
    @goal.build_goal_image unless @goal.image.present?
  end

  def crop
    @goal = Goal.find(params[:id])
    @goal_image = @goal.try(:goal_image)
    if @goal_image.present? && @goal_image.update_attributes(params[:goal][:goal_image_attributes])
      if request.xhr?
        head :no_content
      else
        redirect_to edit_goal_path(@goal), notice: 'Done cropping. Refresh the page.'
      end
    end
  end

  def update
    @goal = current_admin_user.present? ? Goal.find(params[:id]) : current_user.goals.find(params[:id])
    @goal.update_attributes(params[:goal])

    if request.xhr?
      respond_with @goal
    else
      redirect_to edit_goal_path(@goal), notice: 'Goal updated.'
    end
  end

  def destroy
    @goal = current_user.goals.find(params[:id])
    respond_with @goal.destroy
  end
  
  def autoassign_image
    goal = Goal.find(params[:id])
    goal.autoassign_image if goal.remote_image_url.blank?
    respond_with goal
  end
  
  def featured
    @goals = Goal.where(:featured => true).order("id desc").all
    respond_with @goals
  end

  def pathways
    @goal = Goal.find(params[:id])
    respond_with @goal.pathways
  end
  
  def add_to_lifelist
    @goal = Goal.find(params[:id])
    respond_with @goal.copy_to_user(current_user)
  end

  def add_to_doneit
    @goal = Goal.find(params[:id])
    respond_with @goal.copy_to_user(current_user, {:copy_steps => false, :status => "Done"})
  end

  def toggle_vote
    @goal = Goal.unscoped.find(params[:id])
    if current_user.voted_on? @goal
      current_user.unvote_for(@goal)
    else
      current_user.vote_for(@goal)
    end

    render json: @goal.as_json(methods: :votes_count)
  end

  def sort
    @goal = current_user.goals.find(params[:id])
    @goal.position = params[:goal][:position]
    @goal.save!
    respond_with @goal
  end
end

lifelist-master/app/controllers/users/goals_controller.rb
class Users::GoalsController < ApplicationController
  # before_filter :authenticate_user!, except: [:index, :show]
  before_filter :authenticate_admin_user!, only: [:edit, :crop]
  before_filter :find_user, only: [:index, :show]
  respond_to :json

  def index
    respond_to do |format|
      format.html { redirect_to UsersController.helpers.profile_path(@user) }
      format.json { respond_with @user.goals.as_json(methods: :feature_image_url) }
    end
  end

  def show
    respond_to do |format|
      format.html { render template: 'users/show' }
      format.json { respond_with @user.goals.find(params[:id]).as_json(methods: :feature_image_url) }
    end
  end

  def create
    respond_with current_user.goals.create(params[:goal]), location: goals_url
  end

  def edit
    @goal = Goal.find(params[:id])
    @goal.build_goal_image unless @goal.image.present?
  end

  def update
    @goal = current_admin_user.present? ? Goal.find(params[:id]) : current_user.goals.find(params[:id])

    if params.has_key? :publish
      params[:publish] ? @goal.publish! : @goal.unpublish!
    end
    @goal.update_attributes(params[:goal])

    if request.xhr?
      render json: @goal.as_json(methods: :feature_image_url)
    else
      redirect_to edit_goal_path(@goal), notice: 'Goal updated.'
    end
  end

  def destroy
    @goal = current_user.goals.find(params[:id])
    respond_with @goal.destroy
  end

  def autoassign_image
    goal = Goal.find(params[:id])
    goal.autoassign_image if goal.remote_image_url.blank?
    respond_with goal
  end

  def featured
    @goals = Goal.where(:featured => true).order("id desc").all
    respond_with @goals
  end

  def sort
    @goal = current_user.goals.find(params[:id])
    @goal.position = params[:goal][:position]
    @goal.save!
    respond_with @goal
  end
end

lifelist-master/app/views/goals/_cropper.html.haml
- version = Goal.image_version_at(index)
- version_widths = { one_half: 460, one_third: 300, two_thirds: 620 }
.explore_item.cropper{ class: Goal.span_class_at(index) }
  = image_tag goal.image_url, class: 'jwindowcrop', data: { version: version, width: version_widths[version] }

  - %w(x y w h).each do |option|
    = f.hidden_field "#{version}_#{option}"

lifelist-master/app/views/goals/_goal.html.haml
- crop_form_builder ||= nil
.explore_item.viewer{ class: Goal.span_class_at(index) }
  %a{:href => "/goals/#{goal.id}"}
    .explore_image{:style => "background-image: url(#{goal.feature_image_url(index)});"}
    .title
      = goal.name
    .btn-toolbar.list-actions
      %a.btn.btn-secondary.add-goal{"data-id" => goal.id}
        %i.icon-add
      %a.btn.btn-secondary.done-it{"data-id" => goal.id}
        %i.icon-ok
    - if current_admin_user.present?
      .btn-toolbar.edit-actions
        - if crop_form_builder.present?
          = link_to 'crop', '#', data: { action: 'start-cropping', id: goal.id }, class: 'btn btn-small btn-secondary'
        - else
          = link_to 'edit image', edit_goal_path(goal), class: 'btn btn-small btn-secondary'
- if crop_form_builder.present?
  = render partial: 'goals/cropper', locals: { goal: goal, index: index, f: crop_form_builder }

lifelist-master/app/views/goals/edit.html.haml
- content_for :head do
  = stylesheet_link_tag 'jwindowcrop/jWindowCrop'
  = javascript_include_tag 'jwindowcrop/jquery.jWindowCrop'
  = javascript_include_tag 'spinjs/index'

#explore-wrap.container-fluid
  %h1 Edit Goal
  = form_for @goal do |f|
    = f.fields_for :goal_image do |goal_image_fields|
      .fileupload.fileupload-new{"data-provides" => "fileupload"}
        .input-append
          .uneditable-input.span3
            %i.icon-file.fileupload-exists
            %span.fileupload-preview
          %span.btn.btn-file
            %span.fileupload-new Select file
            %span.fileupload-exists Change
            = goal_image_fields.file_field :image
          %a.btn.fileupload-exists{"data-dismiss" => "fileupload", :href => "#"} Remove

    .btn-group= f.submit 'Upload image', class: 'btn btn-large btn-primary'

  = form_for @goal, url: crop_goal_path(@goal), html: { id: :crop_goal }, remote: true do |f|
    = f.fields_for :goal_image do |goal_image_fields|
      = render partial: 'explore/explore_rows', locals: { goals: [@goal, @goal, @goal],
                                                          sequence_offset: 2,
                                                          crop_form_builder: goal_image_fields }

    .btn-group
      = f.submit 'Crop', class: 'btn btn-large btn-primary'

lifelist-master/app/views/goals/show.html.haml
.explore_item
  .explore_image{:style => "background-image: url(#{@goal.feature_image_url(0)});"}
  .title
    = @goal.name

.pathways
  - @goal.pathways.each do |pathway|
    .pathway{ data: {id: pathway.id} }
      =#pathway.name
      .pathway-meta.clearfix
        = image_tag pathway.user.try(:avatar_url, :thumb), class: 'user-thumb pull-left'
        .user-meta.pull-left
          .user-name
            %strong= pathway.user.try(:full_name) || 'Anonymous'
          .user-location
            %i.icon-location
            = pathway.user.try(:location)
        = link_to '#upvote', class: 'btn pull-right', data: { action: :upvote } do
          - if pathway.votes.present?
            %i.icon-heart
            #{pathway.votes.count}
          - else
            %i.icon-heart
            0
      %ol.pathway-steps.step-list
        - pathway.steps.each do |step|
          %li= step.name